# configs/presets/weather.yaml
# ======================================================
# Weather presets for free-space optical channels
# These map directly to sequence_ext.physics.profiles.WEATHER_PRESETS
# ======================================================

clear:
  attenuation_db_per_km: 0.05
  cn2: 1.0e-15
  pointing_sigma_urad: 3.0

fog:
  attenuation_db_per_km: 0.30
  cn2: 1.0e-14
  pointing_sigma_urad: 8.0

rain:
  attenuation_db_per_km: 0.15
  cn2: 5.0e-15
  pointing_sigma_urad: 5.0
