# configs/scenario1_uneven.yaml
# ======================================================
# Scenario 1b – Uneven fiber distances (A–C–B)
# Baseline benchmarking with asymmetric link lengths
# ======================================================

scenario:
  name: scenario1_uneven
  pulse_rate_hz: 50000000    # 50 MHz
  duration_s: 2.0
  output_dir: data/runs/sc1_uneven

devices:
  detector_eta: 0.8
  detector_dark_per_gate: 1e-6
  detector_dead_time_ns: 60
  detector_afterpulse: 0.02
  bsm_visibility: 0.98
  coincidence_window_ps: 500

# No weather – fiber only
weather: null
