# configs/scenario2_moving.yaml
# ======================================================
# Scenario 2 – Moving terminal with free-space optical link
# Models satellite/UAV-to-ground MDI-QKD with weather presets
# ======================================================

scenario:
  name: scenario2_moving
  pulse_rate_hz: 50000000    # 50 MHz
  duration_s: 5.0
  output_dir: data/runs/sc2_moving

devices:
  detector_eta: 0.9
  detector_dark_per_gate: 1e-7
  detector_dead_time_ns: 40
  detector_afterpulse: 0.01
  bsm_visibility: 0.99
  coincidence_window_ps: 300

# Weather can be a preset ("clear", "fog", "rain") or inline config
weather: "clear"
