# configs/scenario4_uk_opt.yaml
# ======================================================
# Scenario 4 – UK-wide relay optimization
# Sweep relay candidates and choose best BSM placement
# ======================================================

scenario:
  name: scenario4_uk_opt
  pulse_rate_hz: 50000000    # 50 MHz before channel loss
  duration_s: 10.0
  output_dir: data/runs/sc4_uk_opt

devices:
  detector_eta: 0.9
  detector_dark_per_gate: 1e-7
  detector_dead_time_ns: 40
  detector_afterpulse: 0.01
  bsm_visibility: 0.99
  coincidence_window_ps: 250

# Fiber network only; no weather effects
weather: null
