# configs/scenario3_city.yaml
# ======================================================
# Scenario 3 – Urban city fiber network
# Mesh/star hybrid with routing + utilization metrics
# ======================================================

scenario:
  name: scenario3_city
  pulse_rate_hz: 40000000    # 40 MHz
  duration_s: 3.0
  output_dir: data/runs/sc3_city

devices:
  detector_eta: 0.82
  detector_dark_per_gate: 8e-7
  detector_dead_time_ns: 55
  detector_afterpulse: 0.018
  bsm_visibility: 0.985
  coincidence_window_ps: 450

# Fiber-only; no weather
weather: null
